[workspace]
members = ["config-lua"]

[package]
name = "video-spider"
version = "0.0.1"
edition = "2024"

[dependencies]
url = { version = "2.5" }
config = { version = "0.15" }

[dependencies.config-lua]
path = "config-lua"
