name: Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    name: Publishing for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    permissions:
      contents: write
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        rust: [stable]
        include:
          - os: ubuntu-latest
            artifact_prefix: linux
            target: x86_64-unknown-linux-gnu
            binary_postfix: ""
          - os: windows-latest
            artifact_prefix: windows
            target: x86_64-pc-windows-msvc
            binary_postfix: ".exe"

    steps:
      - name: Installing Rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}
          target: ${{ matrix.target }}
          override: true
      - name: Checking out sources
        uses: actions/checkout@v1
      - name: Buiding cli package
        run: cargo build -p videospidercli --release --target ${{ matrix.target }}
      - name: Buiding tui package
        run: cargo build -p videospidertui --release --target ${{ matrix.target }}
      - name: Packaging final binary
        shell: bash
        run: |
          cd target/${{ matrix.target }}/release
          # videospidercli
          BINARY_NAME=videospidercli${{ matrix.binary_postfix }}
          RELEASE_NAME=videospidercli-${{ matrix.artifact_prefix }}
          strip $BINARY_NAME
          tar czvf $RELEASE_NAME.tar.gz $BINARY_NAME
          if [[ ${{ runner.os }} == 'Windows' ]]; then
            certutil -hashfile $RELEASE_NAME.tar.gz sha256 | grep -E [A-Fa-f0-9]{64} > $RELEASE_NAME.sha256
          else
            shasum -a 256 $RELEASE_NAME.tar.gz > $RELEASE_NAME.sha256
          fi
          # videospidertui
          BINARY_NAME=videospidertui${{ matrix.binary_postfix }}
          RELEASE_NAME=videospidertui-${{ matrix.artifact_prefix }}
          strip $BINARY_NAME
          tar czvf $RELEASE_NAME.tar.gz $BINARY_NAME
          if [[ ${{ runner.os }} == 'Windows' ]]; then
            certutil -hashfile $RELEASE_NAME.tar.gz sha256 | grep -E [A-Fa-f0-9]{64} > $RELEASE_NAME.sha256
          else
            shasum -a 256 $RELEASE_NAME.tar.gz > $RELEASE_NAME.sha256
          fi
      - name: Release assets
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: false
          files: |
            target/${{ matrix.target }}/release/videospidercli-${{ matrix.artifact_prefix }}.tar.gz
            target/${{ matrix.target }}/release/videospidercli-${{ matrix.artifact_prefix }}.sha256
            target/${{ matrix.target }}/release/videospidertui-${{ matrix.artifact_prefix }}.tar.gz
            target/${{ matrix.target }}/release/videospidertui-${{ matrix.artifact_prefix }}.sha256
            LICENSE
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
